-- ═══════════════════════════════════════════════════════════════════════════
-- ttd_db — the booking table the TTD userscripts read
--
-- Split on purpose:
--   READ   → anyone with the anon key. The Tampermonkey scripts have no login,
--            and they only ever read. Leave this open or they stop working.
--   WRITE  → signed-in users only. Entering and editing bookings happens in
--            the Sevak Registry app, which already has your login.
--
-- So the key in those scripts can look at bookings and nothing else: it cannot
-- add, change or delete a single row.
--
-- Safe to run as many times as you like. It drops no table and rewrites no row.
-- ═══════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────
-- 1. THE TABLE
--    `if not exists` throughout, so an existing ttd_db keeps its data and
--    only gains whatever columns it is missing.
-- ───────────────────────────────────────────────────────────────────────────

create table if not exists public.ttd_db (
  id         bigint generated by default as identity primary key,
  code       text,
  created_at timestamptz default now()
);

-- The lead pilgrim
alter table public.ttd_db add column if not exists sevakname text;
alter table public.ttd_db add column if not exists age       text;
alter table public.ttd_db add column if not exists gender    text;
alter table public.ttd_db add column if not exists idtype    text;
alter table public.ttd_db add column if not exists idnumber  text;

-- Contact + address, used for the booking's own fields
alter table public.ttd_db add column if not exists mobile   text;
alter table public.ttd_db add column if not exists email    text;
alter table public.ttd_db add column if not exists gothram  text;
alter table public.ttd_db add column if not exists city     text;
alter table public.ttd_db add column if not exists state    text;
alter table public.ttd_db add column if not exists country  text;
alter table public.ttd_db add column if not exists pincode  text;

-- Everyone else on the same booking: p2 … p8, i.e. up to eight people in all.
-- The filler reads whatever pN_name columns exist, so adding p9 later is one
-- more block here and nothing else.
do $$
declare n int;
begin
  for n in 2..8 loop
    execute format('alter table public.ttd_db add column if not exists p%s_name     text', n);
    execute format('alter table public.ttd_db add column if not exists p%s_age      text', n);
    execute format('alter table public.ttd_db add column if not exists p%s_gender   text', n);
    execute format('alter table public.ttd_db add column if not exists p%s_idtype   text', n);
    execute format('alter table public.ttd_db add column if not exists p%s_idnumber text', n);
  end loop;
end $$;

-- One booking per code. Without this a double-save quietly makes a second row
-- and the userscript shows the same person twice.
create unique index if not exists ttd_db_code_key on public.ttd_db (code) where code is not null;


-- ───────────────────────────────────────────────────────────────────────────
-- 2. READ IS OPEN, WRITING NEEDS A LOGIN
-- ───────────────────────────────────────────────────────────────────────────

alter table public.ttd_db enable row level security;

drop policy if exists "ttd read"       on public.ttd_db;
drop policy if exists "ttd write"      on public.ttd_db;
drop policy if exists "ttd_all_access" on public.ttd_db;

-- anyone with the anon key may look
create policy "ttd read"
  on public.ttd_db
  for select
  to anon, authenticated
  using (true);

-- only a signed-in user may change anything
create policy "ttd write"
  on public.ttd_db
  for all
  to authenticated
  using (true)
  with check (true);

-- Policies alone are not enough: a role also needs the table privilege. anon
-- gets SELECT and nothing more, so an INSERT with the anon key is refused by
-- Postgres before any policy is even consulted.
revoke all    on table public.ttd_db from anon;
grant  select on table public.ttd_db to   anon;
grant  select, insert, update, delete on table public.ttd_db to authenticated;

grant usage, select on all sequences in schema public to authenticated;


-- ───────────────────────────────────────────────────────────────────────────
-- 3. WAKE THE API — its schema cache is stale after an `alter table`
-- ───────────────────────────────────────────────────────────────────────────

notify pgrst, 'reload schema';


-- ═══════════════════════════════════════════════════════════════════════════
-- CHECKS — select one and press Run.
-- ═══════════════════════════════════════════════════════════════════════════

-- CHECK A — anon should show SELECT only. Any INSERT/UPDATE/DELETE row here
--           means the scripts could also write, which is not what you asked for.
--
-- select grantee, privilege_type
--   from information_schema.role_table_grants
--  where table_schema='public' and table_name='ttd_db'
--    and grantee in ('anon','authenticated')
--  order by grantee, privilege_type;

-- CHECK B — the columns the filler expects.
--
-- select column_name from information_schema.columns
--  where table_schema='public' and table_name='ttd_db' order by column_name;
