-- ═══════════════════════════════════════════════════════════════════════════
-- Control room — drive every open userscript session from the app
--
-- Two additions to what ttd_commands already does:
--
--   ttd_devices   every tab says "I am here, this is my team and who I have
--                 selected" every few seconds, so the app can list them.
--   payload       a command can now carry settings, not just a service name:
--                 the dates to try, the ticket count, who to book, the time
--                 to fire.
--
-- Run supabase-ttd-relay.sql first (it creates ttd_commands). This adds to it.
--
-- ─── THE SAME EXCEPTION, FOR THE SAME REASON ───────────────────────────────
-- Both tables are open to the anon key for read and write, because the
-- userscript has no login and has to both report in and take instructions.
-- What they hold is operational, not personal: a device nickname, a team code,
-- a member code, a timestamp. No names, no numbers, no addresses.
-- `customers` stays signed-in-only. `ttd_db` stays read-only to anon.
--
-- Safe to run as many times as you like.
-- ═══════════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────────
-- 1. COMMANDS CAN CARRY SETTINGS
-- ───────────────────────────────────────────────────────────────────────────

create table if not exists public.ttd_commands (
  id         bigint generated by default as identity primary key,
  room       text        not null default 'default',
  cmd        text        not null,
  target     text,
  issued_by  text,
  created_at timestamptz not null default now()
);

alter table public.ttd_commands add column if not exists payload jsonb;
alter table public.ttd_commands add column if not exists to_device text;   -- null = everyone

create index if not exists ttd_commands_room_id_idx on public.ttd_commands (room, id desc);

alter table public.ttd_commands enable row level security;
drop policy if exists "commands open" on public.ttd_commands;
create policy "commands open" on public.ttd_commands
  for all to anon, authenticated using (true) with check (true);

grant select, insert on table public.ttd_commands to anon, authenticated;
revoke update, delete on table public.ttd_commands from anon;


-- ───────────────────────────────────────────────────────────────────────────
-- 2. WHO IS ONLINE
--
--    One row per device, replaced on every heartbeat. `device` is the primary
--    key so a tab that reconnects updates its row instead of adding another —
--    otherwise a laptop left open all day would fill the table.
-- ───────────────────────────────────────────────────────────────────────────

create table if not exists public.ttd_devices (
  device     text primary key,
  room       text        not null default 'default',
  team       text,                      -- the team code that tab has loaded
  picked     text,                      -- the member code ⚡ FILL would act on
  service    text,                      -- the service it is set to open
  page       text,                      -- roughly where it is in the flow
  running    boolean     not null default false,
  seen_at    timestamptz not null default now()
);

-- Added after the first version: a name you choose, and the settings the
-- device is actually holding, so a card shows what it will do rather than
-- only who it is.
alter table public.ttd_devices add column if not exists label   text;          -- "Ravi laptop"
alter table public.ttd_devices add column if not exists dates   text;          -- dates it will try
alter table public.ttd_devices add column if not exists tickets integer;
alter table public.ttd_devices add column if not exists fire_at text;          -- next scheduled IST time
alter table public.ttd_devices add column if not exists cfg_at  timestamptz;   -- when a push last landed
alter table public.ttd_devices add column if not exists cfg_by  text;          -- who sent it

create index if not exists ttd_devices_room_idx on public.ttd_devices (room, seen_at desc);

alter table public.ttd_devices enable row level security;
drop policy if exists "devices open" on public.ttd_devices;
create policy "devices open" on public.ttd_devices
  for all to anon, authenticated using (true) with check (true);

-- A heartbeat is an upsert, so INSERT and UPDATE are both needed. DELETE is
-- not: a device that stops reporting simply goes stale, and the app hides it.
grant select, insert, update on table public.ttd_devices to anon, authenticated;
revoke delete on table public.ttd_devices from anon;

grant usage, select on all sequences in schema public to anon, authenticated;

notify pgrst, 'reload schema';


-- ═══════════════════════════════════════════════════════════════════════════
-- CHECKS
--
-- select grantee, string_agg(privilege_type,', ' order by privilege_type)
--   from information_schema.role_table_grants
--  where table_schema='public' and table_name in ('ttd_commands','ttd_devices')
--    and grantee='anon' group by grantee;
--
-- select device, room, team, picked, running, seen_at from public.ttd_devices
--  order by seen_at desc;
--
-- Housekeeping, whenever you like:
-- delete from public.ttd_commands where created_at < now() - interval '1 day';
-- delete from public.ttd_devices  where seen_at    < now() - interval '7 days';
-- ═══════════════════════════════════════════════════════════════════════════
