-- ═══════════════════════════════════════════════════════════════════════════
-- ttd_commands — one panel, every laptop
--
-- A command board. The panel you are sitting at writes one row; every tab on
-- every machine running the userscript reads it within a second and acts.
-- No server, no localhost, no port forwarding — it rides on the Supabase you
-- already have.
--
-- ─── READ THIS BEFORE RUNNING ──────────────────────────────────────────────
--
-- This table is open to the anon key for BOTH reading and writing, and it has
-- to be: the userscript has no login, and a tab on another laptop must be able
-- to both obey commands and report that it did.
--
-- That is a deliberate exception, and it is safe only because of what the
-- table holds: a service name and a timestamp. No names, no phone numbers, no
-- registry data. The worst anyone with your key could do is make your tabs
-- open a booking page.
--
-- `customers` stays signed-in-only. `ttd_db` stays read-only to anon. Nothing
-- here changes either.
--
-- Safe to run as many times as you like.
-- ═══════════════════════════════════════════════════════════════════════════


create table if not exists public.ttd_commands (
  id         bigint generated by default as identity primary key,
  room       text        not null default 'default',   -- your squad's channel
  cmd        text        not null,                     -- 'open' | 'stop' | 'ping'
  target     text,                                     -- the service to open
  issued_by  text,                                     -- which device sent it
  created_at timestamptz not null default now()
);

-- Tabs ask "anything newer than what I last saw, on my channel?" — this is the
-- index that makes that a lookup rather than a table scan every second.
create index if not exists ttd_commands_room_id_idx
  on public.ttd_commands (room, id desc);

alter table public.ttd_commands enable row level security;

drop policy if exists "commands open" on public.ttd_commands;
create policy "commands open"
  on public.ttd_commands
  for all
  to anon, authenticated
  using (true)
  with check (true);

grant select, insert on table public.ttd_commands to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Nobody edits or deletes a command; they are a log. Withholding UPDATE and
-- DELETE means a stray key cannot rewrite history or wipe the board.
revoke update, delete on table public.ttd_commands from anon;


-- ───────────────────────────────────────────────────────────────────────────
-- Housekeeping. Rows older than a day are of no use to anyone.
-- Run it whenever, or leave it — a few thousand rows costs nothing.
-- ───────────────────────────────────────────────────────────────────────────
-- delete from public.ttd_commands where created_at < now() - interval '1 day';

notify pgrst, 'reload schema';


-- ═══════════════════════════════════════════════════════════════════════════
-- CHECK — anon should show SELECT and INSERT, and nothing else.
--
-- select grantee, string_agg(privilege_type, ', ' order by privilege_type)
--   from information_schema.role_table_grants
--  where table_schema='public' and table_name='ttd_commands'
--    and grantee in ('anon','authenticated')
--  group by grantee;
-- ═══════════════════════════════════════════════════════════════════════════
